"""Initialize database tables and perform data loading

Revision ID: 081e300f5db4
Revises: 
Create Date: 2021-01-14 21:24:57.669939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

import csv
from collections import namedtuple
from project5.main.models import Category, Meal


# revision identifiers, used by Alembic.
revision = '081e300f5db4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    categories_tbl = op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    meals_tbl = op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('picture', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    session = orm.Session(bind=op.get_bind())

    with open('data/delivery_categories.csv', newline='') as categories_csv:
        reader = csv.reader(categories_csv, delimiter=',')
        Data = namedtuple("Data", next(reader))  # get names from column headers
        for data in map(Data._make, reader):
            session.add(Category(id=data.id, title=data.title))
        session.commit()

    with open('data/delivery_items.csv', newline='') as meals_csv:
        reader = csv.reader(meals_csv, delimiter=',', quotechar='"')
        Data = namedtuple("Data", next(reader))  # get names from column headers
        for data in map(Data._make, reader):
            session.add(
                Meal(
                    id=data.id,
                    category_id=data.category_id,
                    title=data.title,
                    price=data.price,
                    description=data.description,
                    picture=data.picture
                )
            )
        session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meals')
    op.drop_table('categories')
    # ### end Alembic commands ###
