"""empty message

Revision ID: 63109b98437a
Revises: 
Create Date: 2021-01-22 12:42:45.679064

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import orm
import csv
from collections import namedtuple
from project5.showcase.models import Category, Meal, OrderStatus


# revision identifiers, used by Alembic.
revision = '63109b98437a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail')
    )
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('picture', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_meals',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], )
    )
    # ### end Alembic commands ###

    session = orm.Session(bind=op.get_bind())

    session.add_all([
        OrderStatus(id=0, name='Принят'),
        OrderStatus(name='В пути'),
        OrderStatus(name='Доставлен'),
        OrderStatus(name='Отменен')
    ])
    session.commit()

    with open('data/delivery_categories.csv', newline='') as categories_csv:
        reader = csv.reader(categories_csv, delimiter=',')
        Data = namedtuple("Data", next(reader))  # get names from column headers
        for data in map(Data._make, reader):
            session.add(Category(id=data.id, title=data.title))
        session.commit()

    with open('data/delivery_items.csv', newline='') as meals_csv:
        reader = csv.reader(meals_csv, delimiter=',', quotechar='"')
        Data = namedtuple("Data", next(reader))  # get names from column headers
        for data in map(Data._make, reader):
            session.add(
                Meal(
                    id=data.id,
                    category_id=data.category_id,
                    title=data.title,
                    price=data.price,
                    description=data.description,
                    picture=data.picture
                )
            )
        session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_meals')
    op.drop_table('orders')
    op.drop_table('meals')
    op.drop_table('order_status')
    op.drop_table('customers')
    op.drop_table('categories')
    # ### end Alembic commands ###
